// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

// ...



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBb_rF_27xuxALMgJKEXeDC3ygzhpJiJk',
    appId: '1:185738321235:web:5285ae0ee2228360bed5a6',
    messagingSenderId: '185738321235',
    projectId: 'mytodo-6dad7',
    authDomain: 'mytodo-6dad7.firebaseapp.com',
    storageBucket: 'mytodo-6dad7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jbe6bpnwwp-tqQ9pB9HWRQCh8-Fgc-A',
    appId: '1:185738321235:android:6d8b995aae6119ffbed5a6',
    messagingSenderId: '185738321235',
    projectId: 'mytodo-6dad7',
    storageBucket: 'mytodo-6dad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzsFe5CGbwhZ8GmTXeOQ0JGRXPuAretM',
    appId: '1:185738321235:ios:d144e84089bc088abed5a6',
    messagingSenderId: '185738321235',
    projectId: 'mytodo-6dad7',
    storageBucket: 'mytodo-6dad7.appspot.com',
    iosBundleId: 'com.example.myTodo',
  );
}
